name: rdflib
description: A pure Dart package for working with RDF (resource description framework).
version: 0.2.11
homepage: https://github.com/anusii/rdflib
repository: https://github.com/anusii/rdflib

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.2.2
  logging: ^1.2.0
  petitparser: ^6.0.2
  uuid: ^4.4.1
  universal_io: ^2.2.2

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
